name: Packer CI

on:
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  packer-ci:
    name: Packer Validation and Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up HashiCorp Packer using the correct version
    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "1.11.2" 
    
    # Run packer init to install the necessary plugins
    - name: Run packer init
      run: |
        packer init .

        
    - name: Run packer fmt
      id: fmt
      run: |
        packer fmt -check .
      
      # Fail if packer fmt makes changes
      continue-on-error: false
      if: failure() # This ensures that the job fails if packer fmt makes modifications

    - name: Run packer validate
      id: validate
      working-directory: packer
      run: |
        packer validate packertemp.pkr.hcl
