name: WebApp CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name : pr-check
    runs-on: ubuntu-latest

    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }} 
      APP_PORT: ${{ secrets.APP_PORT }} 
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PostgreSQL
      run: |
        sudo apt update
        sudo apt install -y postgresql postgresql-contrib
        sudo systemctl start postgresql

    - name: Set up Node.js using GitHub Action
      uses: actions/setup-node@v3
      with:
          node-version: '18.x'
    
    - name: Install npm dependencies
      run: npm ci

      
    - name: Set up PostgreSQL user and database
      run: |
        sudo -i -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
        npx sequelize-cli db:create

    - name: Run tests
      run: npm test -- --exit
